# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=200)),
                ('git_url', models.CharField(max_length=1000)),
                ('docker_file', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('application_name', models.CharField(choices=[('APPLICATION_NODE_JS', 'Node JS')], max_length=100)),
                ('status', models.CharField(choices=[('STATUS_FORCREATE', 'For Create'), ('STATUS_FORMODIFY', 'For Modify'), ('STATUS_FORDELETE', 'For Delete'), ('STATUS_CREATED', 'Created'), ('STATUS_DELETED', 'Delete'), ('STATUS_MODIFIED', 'Modified')], max_length=100)),
                ('container_url', models.CharField(max_length=1000)),
                ('devstack_container_id', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('last_update_date', models.DateTimeField(verbose_name='date updated')),
                ('created_by', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STATUS_FORCREATE', 'For Create'), ('STATUS_FORMODIFY', 'For Modify'), ('STATUS_FORDELETE', 'For Delete'), ('STATUS_CREATED', 'Created'), ('STATUS_DELETED', 'Delete'), ('STATUS_MODIFIED', 'Modified')], max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('last_update_date', models.DateTimeField(verbose_name='date updated')),
                ('created_by', models.CharField(max_length=100)),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccloud.Container')),
            ],
        ),
    ]
