# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160916194808 on 2016-11-02 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccloud', '0006_auto_20161101_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='openstack_node_id',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='cluster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='ccloud.Cluster'),
        ),
    ]
